### ISSUE TITLE
Nodepool with template observe fail

### ISSUE THREAD

**Issue by dcharbonnier** [edixos/provider-ovh#13]
Using 0.37.0

When requesting a Nodepool with a template:
```
spec:
  forProvider:
    flavorName: b2-15
    kubeIdRef:
      name: k-XXX-ovh
    serviceName: XXX
    maxNodes: 30
    minNodes: 1
    autoscale: true
    monthlyBilled: false
    name: b2-15
    template:
      - metadata:
          - labels:
              type: agents-intensive
        spec:
          - unschedulable: false
            taints:
              - effect: "NoSchedule"
                key: "type"
                value: "agents-intensive"
  providerConfigRef:
    name: ovh-default

```
Synchronization fail:
```
conditions:
    - lastTransitionTime: '2024-03-04T18:17:00Z'
      message: >-
        observe failed: cannot run refresh: refresh failed: Missing required
        argument: The argument "annotations" is required, but no definition was
        found.

        Missing required argument: The argument "finalizers" is required, but no
        definition was found.
      reason: ReconcileError
      status: 'False'
      type: Synced
```

**Comment by dcharbonnier** [comment]
Tried with 0.36.1, same issue

**Comment by smileisak** [comment]
@dcharbonnier thanks for opening this issue, I'll try to reproduce the issue and let you know. 😃

**Comment by smileisak** [comment]
@dcharbonnier I was able to create a nodepool with this specification:

```yaml
apiVersion: kube.ovh.edixos.io/v1alpha1
kind: NodePool
metadata:
  name: hello-edixos
spec:
  providerConfigRef:
    name: default
  forProvider:
    serviceName: ***
    name: hello-crossplane
    flavorName: b2-7
    desiredNodes: 1
    maxNodes: 1
    minNodes: 1
    monthlyBilled: false
    kubeIdRef:
      name: hello-edixos
    template:
      - metadata:
          - labels:
              type: agents-intensive
            annotations:
              type: agents-intensive
            finalizers:
              - "ovhcloud.com/v1beta1"
              - "ovhcloud.com/v1"
        spec:
          - unschedulable: false
            taints:
              - effect: "NoSchedule"
                key: "type"
                value: "agents-intensive"
```

Looks like the 
```go
Metadata []MetadataInitParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`
```
 is optional from the provider api side, but required value from OVH API. Need to be checked why upjet have generated this api specification like so.
