### ISSUE TITLE
As a user of Crossplane and OVH I would like to cross-reference resources without ID

### ISSUE THREAD

**Issue by ekarlso** [edixos/provider-ovh#22]
The following should be supported instead of **clusterId**:

```
apiVersion: databases.ovh.edixos.io/v1alpha1
kind: ProjectDatabase
metadata:
  name: demo-0
  namespace: cp-demo
spec:
  providerConfigRef:
    name: provider-ovh
  forProvider:
    serviceName: xx
    engine: redis
    version: "7.0"
    plan: "essential"
    flavor: db1-4
    nodes:
      - networkId: xx
        subnetId: xx
        region: GRA
  publishConnectionDetailsTo:
    configRef:
      # name: staging-01
      name: staging-01
    name: redis-demo-0
---
# https://redis.io/docs/latest/operate/oss_and_stack/management/security/acl/
apiVersion: databases.ovh.edixos.io/v1alpha1
kind: ProjectDatabaseRedisUser
metadata:
  name: demo
  namespace: cp-demo
spec:
  providerConfigRef:
    name: provider-ovh
  forProvider:
    serviceName: xxx
    name: demo
    clusterIdRef:
      name: demo-0
  publishConnectionDetailsTo:
    configRef:
      # name: staging-01
      name: default
    name: redis-demo-0-user
---
```
